alias free="free -m"
alias update="sudo aptitude update"
alias install="sudo aptitude install"
alias upgrade="sudo aptitude safe-upgrade"
alias remove="sudo aptitude remove"
alias l="ls -lahF"
alias up!="update && upgrade"
alias gv="gvim . &>/dev/null"

alias u="unicorn -p 4567"
alias ur="unicorn_rails -p 3000"

alias gst="git status"
alias gd="git diff"
alias gc="git commit -v"
alias gca="git commit -v -a"
alias gb="git branch"
alias gba="git branch -a"
alias gm="git merge"
alias gmv="git mv"
alias ga="git add"
alias gco="git checkout"
alias gsr="git svn rebase"
alias gsd="git svn dcommit"

alias up="git push origin `parse_git_this_branch`"
alias down="git pull origin `parse_git_this_branch`"
alias uph="git push heroku `parse_git_this_branch`"

alias r="script/rails"
alias rs="r s"
alias rg="r g"
alias rc="r c"

alias gem+="rbx -S gem install --no-rdoc --no-ri"
alias gem-="rbx -S gem uninstall"
alias gem^="rbx -S gem update --no-rdoc --no-ri"
alias gem^!="rbx -S gem update --system"
alias irb="rbx"
alias ruby="rbx -S"
