alias free="free -m"
alias update="sudo aptitude update"
alias install="sudo aptitude install"
alias upgrade="sudo aptitude safe-upgrade"
alias remove="sudo aptitude remove"
alias l="ls -lahF"
alias up!="update && upgrade"

alias u="unicorn -p 4567"
alias ur="unicorn_rails -p 3000"

alias gst="git status"
alias gd="git diff"
alias gc="git commit -v"
alias gca="git commit -v -a"
alias gb="git branch"
alias gba="git branch -a"
alias gm="git merge"
alias gmv="git mv"
alias ga="git add"
alias gco="git checkout"

alias up="git push origin `parse_git_this_branch`"
alias down="git pull origin `parse_git_this_branch`"
alias uph="git push heroku `parse_git_this_branch`"

alias meld="~/sources/meld/bin/meld"

alias gem+="sudo gem install --no-rdoc --no-ri"
alias gem-="sudo gem uninstall"
alias gem^="sudo gem update --no-rdoc --no-ri"
alias gem^!="sudo gem update --system"
alias irb="irb --readline -r irb/completion"
