#!/bin/bash

files=(ackrc aliases.bash bash_login bash_logout bashrc functions.bash gemrc git-completion.bash gitconfig gitignore gitk includes.bash irbrc profile rake.bash rdebugc screenrc tmux.conf vimrc)
C=`pwd`

for f in ${files[*]}
do
  if [[ -h ~/.${f} ]]; then
    rm ~/.${f}
  fi
  ln -s ${C}/${f} ~/.${f}
done
