#!/bin/bash

files=(ackrc aliases.bash bash_logout bashrc functions.bash gemrc git-completion.bash gitconfig gitignore gitk includes.bash irbrc profile rake.bash rdebugc screenrc vimrc)
C=`pwd`

for f in ${files[*]}
do
  rm ~/.${f}
  ln -s ${C}/${f} ~/.${f}
done
